### ISSUE TITLE
Enhance the README Documentation

### ISSUE THREAD

**Issue by malaythakur** [malaythakur/Horizon-Minds#4]

**Comment by 10m4y** [comment]
can u pls tag hacktoberfest in issue and assign it to me I would like to work on this issue

**Comment by malaythakur** [comment]
Thank you for your interest in contributing! I've added the Hacktoberfest label to the issue and assigned it to you. Looking forward to your PR. Let me know if you need any further information or clarification. Happy coding! 🎉"

**Comment by malaythakur** [comment]
Big thanks for the PR! Just merged it in—your work’s solid

**Comment by 10m4y** [comment]
Thank you
